// Storage core for DoStuff — vscode-free by design.
//
// This is the single write path for ticket data: sql.js database (wholesale
// export via tmp+rename), `normalize()` migration chokepoint, the mutator/
// tombstone chokepoints for sync, and attachment byte IO. The VSCode
// extension wraps it in `storage.ts` (config resolution, globalState KV,
// workspace.fs-backed StorageFs); the headless CLI runs it directly on
// `node:fs`.
//
// With a storage directory: a single SQLite database at
// <storageDir>/dostuff.db, accessed via sql.js (WASM). Attachment bytes live
// on disk under <storageDir>/attachments/<issueId>/<attachmentId><ext>; the
// DB carries only Attachment metadata.
//
// With no storage directory: the host-provided KV fallback (the extension's
// `globalState`), unchanged from the JSON era. A host that provides no KV
// must always provide a storage directory.
//
// One-shot migration: on first init with a storage directory, any
// pre-existing `<id>.json` ticket files are read, normalised, inserted into
// the DB, then moved into `<storageDir>/legacy-json-backup/` as a recovery
// escape hatch.

import * as nodePath from "node:path";
import * as fs from "node:fs";
import { randomUUID } from "node:crypto";
import initSqlJs, {
  type Database,
  type SqlJsStatic,
} from "sql.js";
import { Emitter } from "./events";
import { silentLogger, type Logger } from "./mcpHost";
import {
  backfillSyncFields,
  deriveGuid,
  formatIssueId,
  isIsoTimestamp,
  isSafePathSegment,
  TOMBSTONE_TTL_MS,
} from "./syncMerge";
import {
  coerceAttachments,
  coerceCommits,
  coerceLinks,
  coercePendingClose,
  coerceTags,
  isPriority,
  isStatus,
  isType,
  type Issue,
  type IssueType,
  type PendingClose,
  type Priority,
  type RecordEntry,
  type Status,
  type StatusEvent,
  type Task,
} from "./types";

/** Persisted deletion witnesses, as read back by `getSyncTombstones`. */
export interface TicketTombstoneRow {
  guid: string;
  deletedAt: string;
  lastId: string;
}
export interface ElementTombstoneRow {
  ticketGuid: string;
  scope: "task" | "attachment";
  elementId: string;
  deletedAt: string;
}
export interface SyncTombstones {
  tickets: TicketTombstoneRow[];
  elements: ElementTombstoneRow[];
}

const DB_FILENAME = "dostuff.db";
/** See `StorageHost.persistDelayMs`. */
export const DEFAULT_PERSIST_DELAY_MS = 250;
const DB_TMP_FILENAME = "dostuff.db.tmp";
const LEGACY_BACKUP_DIR = "legacy-json-backup";
const SCHEMA_VERSION = 1;

/**
 * Content written to the auto-generated `.gitignore` inside the storage folder.
 * Excludes everything inside (the DB file, attachment bytes, the legacy backup
 * folder) but keeps the gitignore itself trackable so teams who commit
 * `.vscode/` see why their tickets are absent.
 */
export const GITIGNORE_CONTENT =
  "# Auto-generated by DoStuff. Ticket data is local to this clone.\n*\n!.gitignore\n";

const SCHEMA_DDL = `
CREATE TABLE IF NOT EXISTS issues (
  id              TEXT PRIMARY KEY,
  number          INTEGER NOT NULL,
  title           TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  verify_criteria TEXT NOT NULL DEFAULT '',
  type            TEXT NOT NULL,
  priority        TEXT NOT NULL,
  status          TEXT NOT NULL,
  created_at      TEXT NOT NULL,
  resolved_at     TEXT,
  guid            TEXT,
  updated_at      TEXT
);
CREATE INDEX IF NOT EXISTS idx_issues_status  ON issues(status);
CREATE INDEX IF NOT EXISTS idx_issues_number  ON issues(number);
CREATE INDEX IF NOT EXISTS idx_issues_created ON issues(created_at DESC);

CREATE TABLE IF NOT EXISTS issue_tasks (
  issue_id  TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  task_id   TEXT NOT NULL,
  position  INTEGER NOT NULL,
  text      TEXT NOT NULL,
  done      INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT,
  PRIMARY KEY (issue_id, task_id)
);
CREATE INDEX IF NOT EXISTS idx_tasks_issue ON issue_tasks(issue_id, position);

CREATE TABLE IF NOT EXISTS issue_tags (
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  tag      TEXT NOT NULL,
  position INTEGER NOT NULL,
  PRIMARY KEY (issue_id, tag)
);
CREATE INDEX IF NOT EXISTS idx_tags_tag ON issue_tags(tag);

CREATE TABLE IF NOT EXISTS issue_attachments (
  issue_id      TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  attachment_id TEXT NOT NULL,
  position      INTEGER NOT NULL,
  name          TEXT NOT NULL,
  mime_type     TEXT NOT NULL,
  size_bytes    INTEGER NOT NULL,
  added_at      TEXT NOT NULL,
  PRIMARY KEY (issue_id, attachment_id)
);

CREATE TABLE IF NOT EXISTS issue_status_history (
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  status   TEXT NOT NULL,
  at       TEXT NOT NULL,
  by       TEXT NOT NULL,
  PRIMARY KEY (issue_id, position)
);

CREATE TABLE IF NOT EXISTS issue_record (
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  at       TEXT NOT NULL,
  author   TEXT NOT NULL,
  source   TEXT,
  text     TEXT NOT NULL,
  PRIMARY KEY (issue_id, position)
);

CREATE TABLE IF NOT EXISTS issue_links (
  source_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  target_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  kind      TEXT NOT NULL,
  position  INTEGER NOT NULL,
  PRIMARY KEY (source_id, target_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_links_target ON issue_links(target_id);

CREATE TABLE IF NOT EXISTS issue_pending_close (
  issue_id TEXT PRIMARY KEY REFERENCES issues(id) ON DELETE CASCADE,
  by       TEXT NOT NULL,
  note     TEXT,
  at       TEXT NOT NULL,
  target   TEXT
);

-- Commit anchors reported against a ticket via MCP update_ticket_progress.
-- Append-only (no delete path, no tombstones); subject/files are derived
-- lazily from the workspace repo, never stored.
CREATE TABLE IF NOT EXISTS issue_commits (
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  sha      TEXT NOT NULL,
  at       TEXT NOT NULL,
  position INTEGER NOT NULL,
  PRIMARY KEY (issue_id, sha)
);

-- Deletion witnesses for git-native sync (docs/plans/ticket-sync/01 §6).
-- Written on every delete even while sync is disabled; without a persisted
-- witness the merge cannot distinguish "deleted here" from "created there".
-- scope 'ticket' rows use element_id = ticket_guid; last_id records the
-- DS-NNN at deletion time (ticket scope only).
CREATE TABLE IF NOT EXISTS sync_tombstones (
  scope       TEXT NOT NULL,
  ticket_guid TEXT NOT NULL,
  element_id  TEXT NOT NULL,
  deleted_at  TEXT NOT NULL,
  last_id     TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (scope, ticket_guid, element_id)
);

CREATE TABLE IF NOT EXISTS schema_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
`;


/**
 * Forward-compat: stamp missing fields on issues loaded from older versions.
 * Enum fields are coerced to safe defaults when the persisted value is invalid;
 * the caller is responsible for surfacing the coercion (e.g. via the output
 * channel) since this is a pure function.
 */
export function normalize(issue: Issue): { issue: Issue; coerced: string[] } {
  const numFromId = parseInt(String(issue.id || "").replace(/^DS-/, ""), 10);
  const coerced: string[] = [];

  let status = issue.status;
  if (!isStatus(status)) {
    coerced.push(`status="${String((issue as any).status)}" → "Thinking"`);
    status = "Thinking";
  }
  let priority = issue.priority;
  if (!isPriority(priority)) {
    coerced.push(`priority="${String((issue as any).priority)}" → "Regular"`);
    priority = "Regular";
  }
  let type = issue.type;
  if (!isType(type)) {
    coerced.push(`type="${String((issue as any).type)}" → "Chore"`);
    type = "Chore";
  }

  return {
    issue: {
      ...issue,
      status,
      priority,
      type,
      number: Number.isFinite((issue as any).number)
        ? (issue as any).number
        : (Number.isFinite(numFromId) ? numFromId : 0),
      record: Array.isArray((issue as any).record) ? (issue as any).record : [],
      statusHistory: Array.isArray(issue.statusHistory) ? issue.statusHistory : [],
      // Keep task `updatedAt` only when ISO-valid; strip bad values rather
      // than throwing (legacy/garbage input must always load).
      tasks: (Array.isArray(issue.tasks) ? issue.tasks : []).map((t) => {
        if (t && typeof t === "object" && "updatedAt" in t && !isIsoTimestamp((t as Task).updatedAt)) {
          const { updatedAt: _bad, ...rest } = t as Task;
          return rest as Task;
        }
        return t;
      }),
      tags: coerceTags((issue as any).tags),
      attachments: coerceAttachments((issue as any).attachments),
      links: coerceLinks((issue as any).links, (issue as any).id),
      resolvedAt: issue.resolvedAt ?? null,
      pendingClose: coercePendingClose((issue as any).pendingClose),
      commits: coerceCommits((issue as any).commits),
      // Sync identity/ordering fields — server-derived, deterministic backfill
      // for legacy data (docs/plans/ticket-sync/01 §2-3).
      ...backfillSyncFields(
        String(issue.id ?? ""),
        String(issue.createdAt ?? ""),
        (issue as any).guid,
        (issue as any).updatedAt,
      ),
    },
    coerced,
  };
}

// ─── host seams ───────────────────────────────────────────────────────────

/**
 * Filesystem operations the store needs, as async string-path calls. The
 * default is `node:fs` (`nodeStorageFs`); the VSCode adapter maps these onto
 * `vscode.workspace.fs` so the extension keeps exactly its historical IO
 * semantics (and the storage test suite keeps its virtual-FS harness).
 */
/**
 * What a store mutation changed. `issues` is the whole (unsorted) cache for
 * consumers that want it; `upserted` / `removed` let subscribers forward a
 * delta instead of re-sending the board, and `reset: true` means the cache
 * was rebuilt wholesale (init, import, merge) so a full refresh is needed.
 */
export interface StoreChange {
  issues: Issue[];
  upserted: Issue[];
  removed: string[];
  reset: boolean;
}

export interface StorageFs {
  readFile(path: string): Promise<Uint8Array>;
  writeFile(path: string, content: Uint8Array): Promise<void>;
  /** Recursive, idempotent mkdir. */
  createDirectory(path: string): Promise<void>;
  /** Missing targets must not throw. */
  delete(path: string, opts?: { recursive?: boolean }): Promise<void>;
  exists(path: string): Promise<boolean>;
  readDirectory(path: string): Promise<Array<[string, "file" | "directory" | "other"]>>;
  /** Must overwrite an existing target (POSIX rename semantics). */
  rename(from: string, to: string): Promise<void>;
}

export const nodeStorageFs: StorageFs = {
  readFile: (p) => fs.promises.readFile(p),
  writeFile: (p, content) => fs.promises.writeFile(p, content),
  createDirectory: async (p) => {
    await fs.promises.mkdir(p, { recursive: true });
  },
  delete: async (p, opts) => {
    await fs.promises.rm(p, { recursive: opts?.recursive ?? false, force: true });
  },
  exists: async (p) => {
    try {
      await fs.promises.stat(p);
      return true;
    } catch {
      return false;
    }
  },
  readDirectory: async (p) => {
    const entries = await fs.promises.readdir(p, { withFileTypes: true });
    return entries.map((d) => [
      d.name,
      d.isFile() ? "file" : d.isDirectory() ? "directory" : "other",
    ]);
  },
  rename: (from, to) => fs.promises.rename(from, to),
};

/** Key-value fallback used when no storage directory exists (extension: globalState). */
export interface KvStore {
  get(): unknown;
  update(value: unknown): Promise<void>;
}

/** Everything the store needs from its host. All resolution stays live (callbacks). */
export interface StorageHost {
  /**
   * Absolute directory holding dostuff.db + attachments/, or null to use the
   * KV fallback. Read at init/reload time and per file operation, so a config
   * change followed by `reload()` picks up the new location.
   */
  storageDir(): string | null;
  /** sql.js WASM bytes. Only called when a storage directory exists. */
  wasmBinary(): Promise<Uint8Array>;
  /** Whether to write the auto-generated `.gitignore` (default true). */
  writeStorageGitignore?(): boolean;
  logger?: Logger;
  kv?: KvStore;
  fs?: StorageFs;
  /**
   * Write-behind delay for persistence (default 250ms). Every mutation
   * commits to the in-memory DB and fires `onChange` immediately; the
   * on-disk image (a wholesale `db.export()` + file write, O(board size)) is
   * written at most once per `persistDelayMs` window (the timer arms on the
   * first dirty mutation — a throttle, so a constant stream of edits still
   * bounds the loss window), or by `flush()` / `close()`. `0` restores the
   * old awaited-per-mutation path.
   * Trade-off: a crash inside the window loses that window's edits; the
   * tmp+rename write stays atomic, so the file is never torn.
   */
  persistDelayMs?: number;
}

// ─── sql.js singleton ─────────────────────────────────────────────────────

let sqlJsPromise: Promise<SqlJsStatic> | null = null;
function loadSqlJs(wasmBinary: Uint8Array): Promise<SqlJsStatic> {
  if (!sqlJsPromise) {
    // Copy into a fresh ArrayBuffer; sql.js mutates the buffer it's given.
    const copy = new Uint8Array(wasmBinary.byteLength);
    copy.set(wasmBinary);
    sqlJsPromise = initSqlJs({ wasmBinary: copy.buffer });
  }
  return sqlJsPromise;
}

export class IssueStoreCore {
  private cache: Issue[] = [];
  private reservedNumber: number = 0;
  private db: Database | null = null;
  private readonly emitter = new Emitter<StoreChange>();
  public readonly onChange = this.emitter.event;
  /** Memoized `list()` order; nulled by `touchCache()` at every cache mutation. */
  private sorted: Issue[] | null = null;
  private readonly logger: Logger;
  private readonly fs: StorageFs;
  // Export queue state — see exportDb().
  private exportRunning: Promise<void> | null = null;
  private exportQueued: Promise<void> | null = null;
  /** Write-behind state: unpersisted mutations pending, and the trailing timer. */
  private dirty = false;
  private persistTimer: ReturnType<typeof setTimeout> | null = null;
  private readonly persistDelayMs: number;

  constructor(private readonly host: StorageHost) {
    this.logger = host.logger ?? silentLogger;
    this.fs = host.fs ?? nodeStorageFs;
    this.persistDelayMs = host.persistDelayMs ?? DEFAULT_PERSIST_DELAY_MS;
  }

  // ─── public API ─────────────────────────────────────────────────────────

  async init(): Promise<void> {
    const folder = this.host.storageDir();
    if (folder) {
      await this.initSqlite(folder);
    } else {
      this.closeDb();
      this.cache = this.loadFromKv();
      this.touchCache();
    }
    this.reservedNumber = this.cache.reduce(
      (max, i) => (Number.isFinite(i.number) && i.number > max ? i.number : max),
      0,
    );
    this.fire({ upserted: [], removed: [], reset: true });
  }

  /**
   * Re-read from disk. Used when the user changes `dostuff.storagePath` at
   * runtime so the in-memory cache picks up the new folder.
   */
  async reload(): Promise<void> {
    this.closeDb();
    this.cache = [];
    this.touchCache();
    this.reservedNumber = 0;
    await this.init();
  }

  /** Append a timestamped line to the host log. */
  appendLog(line: string): void {
    this.logger.info(`[${new Date().toISOString()}] ${line}`);
  }

  /**
   * Issues newest-first by `createdAt`. The sort is memoized across calls
   * (every mutation path calls `touchCache()`), and the key is parsed once
   * per issue rather than twice per comparison — `list()` is called several
   * times per edit by the host, the providers and the sync controller, and
   * used to re-sort the whole board with two `Date` allocations per compare
   * each time. Always returns a fresh array: callers hold it across awaits.
   */
  list(): Issue[] {
    if (!this.sorted) {
      const keyed = this.cache.map((issue, index) => ({
        issue,
        key: Date.parse(issue.createdAt) || 0, // unparsable → oldest
        index,
      }));
      keyed.sort((a, b) => b.key - a.key || a.index - b.index);
      this.sorted = keyed.map((k) => k.issue);
    }
    return [...this.sorted];
  }

  /** Every write to `this.cache` (assignment or in-place) goes through here. */
  private touchCache(): void {
    this.sorted = null;
  }

  private fire(change: Omit<StoreChange, "issues">): void {
    this.emitter.fire({ issues: this.cache, ...change });
  }

  get(id: string): Issue | undefined {
    return this.cache.find((i) => i.id === id);
  }

  /**
   * The single stamping chokepoint (docs/plans/ticket-sync/01 §5). Every UI
   * and MCP mutation funnels through here. Default path: stamp `updatedAt`,
   * mint/carry `guid`, diff-stamp per-task `updatedAt` against the prior
   * ticket, and record element tombstones for tasks/attachments the incoming
   * copy dropped. `preserveTimestamps: true` writes the issue exactly as
   * given and records nothing — the sync controller's apply path is the only
   * intended caller (merged remote state must keep remote timestamps).
   */
  async upsert(issue: Issue, opts?: { preserveTimestamps?: boolean }): Promise<void> {
    const prior = this.cache.find((i) => i.id === issue.id);
    let next = issue;
    if (!opts?.preserveTimestamps) {
      const now = new Date().toISOString();
      next = {
        ...issue,
        guid: issue.guid || prior?.guid || randomUUID(),
        updatedAt: now,
        tasks: stampTasks(issue.tasks, prior?.tasks, now),
      };
    }
    const idx = this.cache.findIndex((i) => i.id === next.id);
    if (idx >= 0) this.cache[idx] = next;
    else this.cache.unshift(next);
    this.touchCache();
    if (this.db) {
      this.runInTransaction(() => {
        if (!opts?.preserveTimestamps && prior) {
          this.recordElementTombstones(this.db!, prior, next, next.updatedAt);
        }
        this.writeIssueRows(this.db!, next);
      });
    }
    await this.schedulePersist();
    this.fire({ upserted: [next], removed: [], reset: false });
  }

  async remove(id: string): Promise<void> {
    const removed = this.cache.find((i) => i.id === id);
    const before = this.cache;
    this.cache = this.cache
      .filter((i) => i.id !== id)
      // Inbound link cleanup: the DB cascades `issue_links` rows where this
      // id was the target, but the in-memory cache still carries the old
      // `links` arrays. Scrub them in sync so reads after `remove()` don't
      // see ghost links.
      .map((i) =>
        i.links.some((l) => l.targetId === id)
          ? { ...i, links: i.links.filter((l) => l.targetId !== id) }
          : i,
      );
    this.touchCache();
    // Survivors whose links were scrubbed are new objects → they changed.
    const scrubbed = this.cache.filter((i) => !before.includes(i));
    if (this.db) {
      this.runInTransaction(() => {
        // Deletion witness for sync — must land in the same transaction as
        // the delete so the two can never diverge (01 §6).
        if (removed) {
          this.recordTicketTombstone(this.db!, removed, new Date().toISOString());
        }
        // Explicit inbound-link cleanup. sql.js's PRAGMA foreign_keys =
        // CASCADE setting has been historically unreliable across exports;
        // doing the DELETE ourselves guarantees no dangling rows survive
        // a round-trip through `exportDb`.
        this.db!.run("DELETE FROM issue_links WHERE target_id = ? OR source_id = ?", [id, id]);
        this.db!.run("DELETE FROM issues WHERE id = ?", [id]);
      });
    }
    await this.schedulePersist();
    await this.deleteIssueAttachments(id);
    this.fire({ upserted: scrubbed, removed: removed ? [id] : [], reset: false });
  }

  async replaceAll(issues: Issue[]): Promise<void> {
    const prior = this.cache;
    // Import path: stamp only-if-missing so export→import round trips keep
    // exported timestamps/guids (01 §5).
    const next = issues.map((i) => ensureSyncFields(i));
    this.cache = [...next];
    this.touchCache();
    this.bumpReserved(this.cache);
    if (this.db) {
      const now = new Date().toISOString();
      const nextById = new Map(next.map((i) => [i.id, i]));
      this.runInTransaction(() => {
        for (const p of prior) {
          const replacement = nextById.get(p.id);
          if (!replacement) this.recordTicketTombstone(this.db!, p, now);
          else this.recordElementTombstones(this.db!, p, replacement, now);
        }
        this.db!.run("DELETE FROM issues");
        for (const i of next) this.writeIssueRows(this.db!, i);
      });
      await this.wipeAttachmentsRoot();
    }
    await this.schedulePersist();
    this.fire({ upserted: [], removed: [], reset: true });
  }

  async mergeAll(issues: Issue[]): Promise<void> {
    const incoming = issues.map((i) => ensureSyncFields(i));
    const priorById = new Map(this.cache.map((i) => [i.id, i]));
    const byId = new Map(priorById);
    for (const i of incoming) byId.set(i.id, i);
    this.cache = [...byId.values()];
    this.touchCache();
    this.bumpReserved(this.cache);
    if (this.db) {
      const now = new Date().toISOString();
      this.runInTransaction(() => {
        for (const i of incoming) {
          const p = priorById.get(i.id);
          if (p) this.recordElementTombstones(this.db!, p, i, now);
          this.writeIssueRows(this.db!, i);
        }
      });
    }
    await this.schedulePersist();
    this.fire({ upserted: [], removed: [], reset: true });
  }

  /**
   * Apply merged remote sync state: upsert fully-merged issues with
   * `preserveTimestamps` semantics, delete specific ids, and never record
   * tombstones (inbound state already carries its own). One transaction, one
   * flush, one `onChange` fire (docs/plans/ticket-sync/01 §9).
   *
   * `removals` = tombstoned tickets + old ids of renumbered tickets;
   * `tombstoned` marks which of those should also lose their attachment dir
   * (a renumbered ticket's dir has already been renamed by the caller).
   */
  async applySync(args: {
    upserts: Issue[];
    removals: string[];
    tombstoned?: string[];
  }): Promise<void> {
    const { upserts, removals } = args;
    const tombstoned = new Set(args.tombstoned ?? []);
    const removalSet = new Set(removals);

    // Cache: drop removals (scrubbing inbound links to them), then upsert.
    const upsertById = new Map(upserts.map((i) => [i.id, i]));
    const survivors = this.cache
      .filter((i) => !removalSet.has(i.id))
      .map((i) =>
        i.links.some((l) => removalSet.has(l.targetId))
          ? { ...i, links: i.links.filter((l) => !removalSet.has(l.targetId)) }
          : i,
      );
    const seen = new Set<string>();
    const nextCache: Issue[] = survivors.map((i) => {
      const replacement = upsertById.get(i.id);
      if (replacement) seen.add(i.id);
      return replacement ?? i;
    });
    for (const i of upserts) {
      if (!seen.has(i.id)) nextCache.unshift(i);
    }
    this.cache = nextCache;
    this.touchCache();
    this.bumpReserved(this.cache);

    if (this.db) {
      this.runInTransaction(() => {
        for (const id of removals) {
          this.db!.run("DELETE FROM issue_links WHERE target_id = ? OR source_id = ?", [id, id]);
          this.db!.run("DELETE FROM issues WHERE id = ?", [id]);
        }
        for (const i of upserts) this.writeIssueRows(this.db!, i);
      });
    }
    await this.schedulePersist();
    for (const id of removals) {
      if (tombstoned.has(id)) await this.deleteIssueAttachments(id);
    }
    this.fire({ upserted: upserts, removed: removals, reset: false });
  }

  /**
   * Read all persisted deletion witnesses (01 §6). The sync controller feeds
   * these into the outbound wire state. Empty (and never written) in the
   * KV fallback — no storage dir ⇒ sync inert.
   */
  getSyncTombstones(): SyncTombstones {
    if (!this.db) return { tickets: [], elements: [] };
    const rows = selectAll<{
      scope: string;
      ticket_guid: string;
      element_id: string;
      deleted_at: string;
      last_id: string;
    }>(this.db, "SELECT * FROM sync_tombstones");
    const tickets: TicketTombstoneRow[] = [];
    const elements: ElementTombstoneRow[] = [];
    for (const r of rows) {
      if (r.scope === "ticket") {
        tickets.push({ guid: r.ticket_guid, deletedAt: r.deleted_at, lastId: r.last_id });
      } else if (r.scope === "task" || r.scope === "attachment") {
        elements.push({
          ticketGuid: r.ticket_guid,
          scope: r.scope,
          elementId: r.element_id,
          deletedAt: r.deleted_at,
        });
      }
    }
    return { tickets, elements };
  }

  /** Ticket-scope deletion witness. Caller wraps in a transaction. */
  private recordTicketTombstone(db: Database, issue: Issue, deletedAt: string): void {
    db.run(
      "INSERT OR REPLACE INTO sync_tombstones (scope, ticket_guid, element_id, deleted_at, last_id) VALUES ('ticket', ?, ?, ?, ?)",
      [issue.guid, issue.guid, deletedAt, issue.id],
    );
  }

  /**
   * Element-scope deletion witnesses: task/attachment ids present on `prior`
   * but absent from `next`. Caller wraps in a transaction.
   */
  private recordElementTombstones(db: Database, prior: Issue, next: Issue, deletedAt: string): void {
    const guid = next.guid || prior.guid;
    const recordDropped = (scope: "task" | "attachment", priorEls: Array<{ id: string }>, nextEls: Array<{ id: string }>) => {
      const kept = new Set(nextEls.map((e) => e.id));
      for (const el of priorEls) {
        if (kept.has(el.id)) continue;
        db.run(
          "INSERT OR REPLACE INTO sync_tombstones (scope, ticket_guid, element_id, deleted_at, last_id) VALUES (?, ?, ?, ?, '')",
          [scope, guid, el.id, deletedAt],
        );
      }
    };
    recordDropped("task", prior.tasks, next.tasks);
    recordDropped("attachment", prior.attachments, next.attachments);
  }

  /** Generate next monotonic ID (DS-001, DS-002, ...). */
  nextId(): string {
    return formatIssueId(this.nextNumber());
  }

  /**
   * Reserve the next monotonic ticket number (1, 2, 3, ...).
   *
   * Race-safe via a monotonic in-memory counter. Each call increments the
   * counter, so two concurrent `nextNumber()` calls cannot collide. The
   * counter rises whether or not the caller follows through with `upsert`, so
   * a user opening then cancelling "New Issue" leaves a gap — that is the
   * intentional trade-off versus collisions on simultaneous creation.
   */
  nextNumber(): number {
    const fromCache = this.cache.reduce(
      (max, i) => (Number.isFinite(i.number) && i.number > max ? i.number : max),
      0,
    );
    const candidate = Math.max(fromCache, this.reservedNumber) + 1;
    this.reservedNumber = candidate;
    return candidate;
  }

  /** Raise the reserved counter so it stays ahead of any imported numbers. */
  private bumpReserved(set: Issue[]): void {
    for (const i of set) {
      if (Number.isFinite(i.number) && i.number > this.reservedNumber) {
        this.reservedNumber = i.number;
      }
    }
  }

  // ─── attachments ────────────────────────────────────────────────────────
  // Attachment bytes live on disk; the DB only holds metadata. Every helper
  // refuses ids that are not a single safe path segment — ids reach these
  // methods from several input surfaces (webview, import, sync, DB hydrate),
  // and this chokepoint keeps a hostile id from ever becoming a traversal.

  /** Root of all attachment binaries: `<storageDir>/attachments`. */
  attachmentsPath(): string | null {
    const folder = this.host.storageDir();
    if (!folder) return null;
    return nodePath.join(folder, "attachments");
  }

  /** True when every provided path component is a single safe segment. */
  private safeAttachmentPath(what: string, ...segments: string[]): boolean {
    for (const s of segments) {
      if (!isSafePathSegment(s)) {
        this.appendLog(`Attachment ${what} refused: unsafe path segment ${JSON.stringify(s)}`);
        return false;
      }
    }
    return true;
  }

  /**
   * Write attachment bytes to `<storageDir>/attachments/<issueId>/<attId><ext>`.
   * Returns false if no storage directory exists (or the ids/ext are not safe
   * path segments). Throws on I/O failure.
   */
  async writeAttachment(
    issueId: string,
    attachmentId: string,
    ext: string,
    bytes: Uint8Array,
  ): Promise<boolean> {
    const root = this.attachmentsPath();
    if (!root) return false;
    if (!this.safeAttachmentPath("write", issueId, `${attachmentId}${ext}`)) return false;
    const dir = nodePath.join(root, issueId);
    try { await this.fs.createDirectory(dir); } catch {}
    const file = nodePath.join(dir, `${attachmentId}${ext}`);
    await this.fs.writeFile(file, bytes);
    return true;
  }

  /**
   * Resolve the on-disk path of an attachment by enumerating the issue's folder.
   * The on-disk filename is `<attachmentId><ext>`; we don't store the extension
   * in metadata because the host already knows it from the original filename.
   */
  async findAttachmentPath(issueId: string, attachmentId: string): Promise<string | null> {
    const root = this.attachmentsPath();
    if (!root) return null;
    if (!this.safeAttachmentPath("lookup", issueId, attachmentId)) return null;
    const dir = nodePath.join(root, issueId);
    let entries: Array<[string, "file" | "directory" | "other"]>;
    try {
      entries = await this.fs.readDirectory(dir);
    } catch {
      return null;
    }
    for (const [name, kind] of entries) {
      if (kind !== "file") continue;
      const dot = name.indexOf(".");
      const baseName = dot >= 0 ? name.slice(0, dot) : name;
      if (baseName === attachmentId) {
        return nodePath.join(dir, name);
      }
    }
    return null;
  }

  /** Read attachment bytes. Throws when the file is missing. */
  async readAttachment(issueId: string, attachmentId: string): Promise<Uint8Array> {
    const p = await this.findAttachmentPath(issueId, attachmentId);
    if (!p) throw new Error(`Attachment file not found for ${issueId}/${attachmentId}`);
    return this.fs.readFile(p);
  }

  /** Remove a single attachment file. No-op when the file doesn't exist. */
  async deleteAttachmentFile(issueId: string, attachmentId: string): Promise<void> {
    const p = await this.findAttachmentPath(issueId, attachmentId);
    if (!p) return;
    try { await this.fs.delete(p); } catch {}
  }

  /** Remove an issue's entire attachments folder. Called from `remove(id)`. */
  private async deleteIssueAttachments(issueId: string): Promise<void> {
    const root = this.attachmentsPath();
    if (!root) return;
    // Recursive delete — the one helper where an unsafe id would be truly
    // destructive. The guard makes a hostile id a logged no-op instead.
    if (!this.safeAttachmentPath("delete", issueId)) return;
    const dir = nodePath.join(root, issueId);
    try {
      await this.fs.delete(dir, { recursive: true });
    } catch {}
  }

  private async wipeAttachmentsRoot(): Promise<void> {
    const root = this.attachmentsPath();
    if (!root) return;
    try {
      await this.fs.delete(root, { recursive: true });
    } catch {}
  }

  // ─── SQLite backend ─────────────────────────────────────────────────────

  /**
   * Write a `.gitignore` inside the storage folder so ticket data is excluded
   * from Git even when `.vscode/` itself is tracked. Idempotent and
   * non-destructive: never overwrites an existing file. Respects the
   * `dostuff.writeStorageGitignore` opt-out setting.
   */
  private async ensureGitignore(dir: string): Promise<void> {
    if (this.host.writeStorageGitignore && !this.host.writeStorageGitignore()) return;
    const gi = nodePath.join(dir, ".gitignore");
    if (await this.fs.exists(gi)) return;
    try {
      await this.fs.writeFile(gi, new TextEncoder().encode(GITIGNORE_CONTENT));
    } catch {}
  }

  private async initSqlite(folder: string): Promise<void> {
    try { await this.fs.createDirectory(folder); } catch {}
    await this.ensureGitignore(folder);

    const wasm = await this.host.wasmBinary();
    const SQL = await loadSqlJs(wasm);
    const dbPath = nodePath.join(folder, DB_FILENAME);

    let existing: Uint8Array | null = null;
    try {
      existing = await this.fs.readFile(dbPath);
    } catch {
      existing = null;
    }

    const db = existing ? new SQL.Database(existing) : new SQL.Database();
    db.run("PRAGMA foreign_keys = ON");
    db.exec(SCHEMA_DDL);
    // Additive columns on pre-existing tables. SQLite has no ADD COLUMN IF
    // NOT EXISTS; the duplicate-column error is the expected steady state on
    // current DBs (fresh DBs get the columns from SCHEMA_DDL directly).
    for (const ddl of [
      "ALTER TABLE issues ADD COLUMN guid TEXT",
      "ALTER TABLE issues ADD COLUMN updated_at TEXT",
      "ALTER TABLE issue_tasks ADD COLUMN updated_at TEXT",
      "ALTER TABLE issue_pending_close ADD COLUMN target TEXT",
    ]) {
      try {
        db.exec(ddl);
      } catch (e) {
        if (!String(e).includes("duplicate column name")) throw e;
      }
    }
    // Local tombstone hygiene: rows older than the sync TTL can never win a
    // merge anyway (docs/plans/ticket-sync/02 §5 GC), so prune them here.
    db.run("DELETE FROM sync_tombstones WHERE deleted_at < ?", [
      new Date(Date.now() - TOMBSTONE_TTL_MS).toISOString(),
    ]);
    this.db = db;

    if (!existing) {
      // Migration sequence (order matters for crash safety):
      //   1. Read+parse all legacy .json files into memory (no DB activity).
      //   2. One synchronous BEGIN/COMMIT block — no awaits between BEGIN and
      //      COMMIT, so no other code can interleave a nested transaction.
      //   3. Stamp schema_meta.
      //   4. Export DB to disk. Crash before this → dostuff.db never appears,
      //      legacy .json files still at top level, next start re-migrates.
      //   5. Move legacy files to backup. Crash here → DB has data, .json files
      //      orphan at top level (harmless; ignored on next start since DB exists).
      const parsed = await this.parseLegacyJsonFiles(folder);
      const t0 = Date.now();
      const migratedIssues: Issue[] = [];
      db.run("BEGIN");
      try {
        for (const p of parsed) {
          if (p.issue) {
            this.writeIssueRows(db, p.issue);
            migratedIssues.push(p.issue);
          }
        }
        db.run("COMMIT");
      } catch (e) {
        try { db.run("ROLLBACK"); } catch {}
        throw e;
      }
      this.setSchemaMeta(db, "version", String(SCHEMA_VERSION));
      this.cache = migratedIssues;
      this.touchCache();
      await this.exportDb();
      await this.moveLegacyFilesToBackup(folder, parsed);
      if (parsed.length > 0) {
        this.appendLog(
          `Migrated ${migratedIssues.length}/${parsed.length} ticket(s) from JSON → SQLite in ${Date.now() - t0}ms.`,
        );
      }
    } else {
      this.cache = this.hydrateFromDb(db);
      this.touchCache();
      const ver = this.getSchemaMeta(db, "version");
      if (ver === null || Number(ver) < SCHEMA_VERSION) {
        // No version stamped, or older — run upgrade hook (no-op today) and stamp.
        this.setSchemaMeta(db, "version", String(SCHEMA_VERSION));
        await this.exportDb();
      } else if (Number(ver) > SCHEMA_VERSION) {
        // Newer DB than this build understands. Don't stamp; warn and continue.
        // Reads use SELECT * so unknown columns/tables are ignored, but write
        // paths can't know about future fields. Best-effort.
        this.appendLog(
          `Warning: DB schema version ${ver} is newer than this build (v${SCHEMA_VERSION}). Some fields may be ignored.`,
        );
      }
    }
  }

  /**
   * Phase 1 of migration: read and parse every `<id>.json` into memory.
   * Performs no DB writes — safe to interleave with concurrent store ops.
   */
  private async parseLegacyJsonFiles(folder: string): Promise<Array<{ name: string; issue: Issue | null }>> {
    let entries: Array<[string, "file" | "directory" | "other"]>;
    try {
      entries = await this.fs.readDirectory(folder);
    } catch {
      return [];
    }
    const jsonFiles = entries.filter(
      ([name, kind]) => kind === "file" && name.endsWith(".json"),
    );
    if (jsonFiles.length === 0) return [];

    const decoder = new TextDecoder();
    return Promise.all(
      jsonFiles.map(async ([name]): Promise<{ name: string; issue: Issue | null }> => {
        const src = nodePath.join(folder, name);
        try {
          const buf = await this.fs.readFile(src);
          const obj = JSON.parse(decoder.decode(buf)) as Issue;
          if (obj && obj.id && obj.title) {
            const { issue: norm, coerced } = normalize(obj);
            if (coerced.length) {
              this.appendLog(`Coerced fields on ${norm.id} (${name}): ${coerced.join(", ")}`);
            }
            return { name, issue: norm };
          }
          this.appendLog(`Skipping ${name} during migration: missing id or title.`);
          return { name, issue: null };
        } catch (e) {
          this.appendLog(`Failed to parse ${name} during migration: ${(e as Error).message}`);
          return { name, issue: null };
        }
      }),
    );
  }

  /**
   * Phase 3 of migration: move every original .json (migrated AND skipped) into
   * `legacy-json-backup/`. Called AFTER the DB has been exported to disk, so a
   * crash here leaves the DB intact and the .json files orphan at top level —
   * which next activation will ignore (DB already exists → skip migration).
   * Best-effort per file; rename failures are logged, not thrown.
   */
  private async moveLegacyFilesToBackup(
    folder: string,
    parsed: Array<{ name: string; issue: Issue | null }>,
  ): Promise<void> {
    if (parsed.length === 0) return;
    const backupDir = nodePath.join(folder, LEGACY_BACKUP_DIR);
    try { await this.fs.createDirectory(backupDir); } catch {}
    await Promise.all(
      parsed.map(async (p) => {
        const src = nodePath.join(folder, p.name);
        try {
          await this.fs.rename(src, nodePath.join(backupDir, p.name));
        } catch (e) {
          this.appendLog(
            `Failed to move ${p.name} to ${LEGACY_BACKUP_DIR}: ${(e as Error).message}`,
          );
        }
      }),
    );
  }

  private hydrateFromDb(db: Database): Issue[] {
    const issueRows = selectAll<{
      id: string;
      number: number;
      title: string;
      description: string;
      verify_criteria: string;
      type: string;
      priority: string;
      status: string;
      created_at: string;
      resolved_at: string | null;
      guid: string | null;
      updated_at: string | null;
    }>(db, "SELECT * FROM issues");

    const tasksByIssue = groupBy(
      selectAll<{
        issue_id: string;
        task_id: string;
        position: number;
        text: string;
        done: number;
        updated_at: string | null;
      }>(db, "SELECT * FROM issue_tasks ORDER BY issue_id, position"),
      (r) => r.issue_id,
    );
    const tagsByIssue = groupBy(
      selectAll<{ issue_id: string; tag: string; position: number }>(
        db,
        "SELECT * FROM issue_tags ORDER BY issue_id, position",
      ),
      (r) => r.issue_id,
    );
    const attsByIssue = groupBy(
      selectAll<{
        issue_id: string;
        attachment_id: string;
        position: number;
        name: string;
        mime_type: string;
        size_bytes: number;
        added_at: string;
      }>(db, "SELECT * FROM issue_attachments ORDER BY issue_id, position"),
      (r) => r.issue_id,
    );
    const historyByIssue = groupBy(
      selectAll<{
        issue_id: string;
        position: number;
        status: string;
        at: string;
        by: string;
      }>(db, "SELECT * FROM issue_status_history ORDER BY issue_id, position"),
      (r) => r.issue_id,
    );
    const recordByIssue = groupBy(
      selectAll<{
        issue_id: string;
        position: number;
        at: string;
        author: string;
        source: string | null;
        text: string;
      }>(db, "SELECT * FROM issue_record ORDER BY issue_id, position"),
      (r) => r.issue_id,
    );
    const linksBySource = groupBy(
      selectAll<{
        source_id: string;
        target_id: string;
        kind: string;
        position: number;
      }>(db, "SELECT * FROM issue_links ORDER BY source_id, position"),
      (r) => r.source_id,
    );
    const commitsByIssue = groupBy(
      selectAll<{
        issue_id: string;
        sha: string;
        at: string;
        position: number;
      }>(db, "SELECT * FROM issue_commits ORDER BY issue_id, position"),
      (r) => r.issue_id,
    );
    // 0-or-1 relation, so a plain Map rather than groupBy. A main-era DB has no
    // such table row for any issue → the map is empty → all pendingClose null.
    const pendingCloseByIssue = new Map<string, PendingClose>();
    for (const r of selectAll<{
      issue_id: string;
      by: string;
      note: string | null;
      at: string;
      target: string | null;
    }>(db, "SELECT * FROM issue_pending_close")) {
      const pc = coercePendingClose({
        by: r.by,
        at: r.at,
        ...(r.note !== null ? { note: r.note } : {}),
        // NULL (pre-target rows / older-build writes) → coercer drops the
        // field → legacy meaning "Closed".
        ...(r.target !== null ? { target: r.target } : {}),
      });
      if (pc) pendingCloseByIssue.set(r.issue_id, pc);
    }

    return issueRows.map((row) => {
      const tasks: Task[] = (tasksByIssue.get(row.id) ?? []).map((t) => ({
        id: t.task_id,
        text: t.text,
        done: t.done !== 0,
        // No eager default for a missing stamp — the sync wire boundary
        // defaults it to the ticket's createdAt (02-merge-spec §5).
        ...(t.updated_at ? { updatedAt: t.updated_at } : {}),
      }));
      const tags = coerceTags((tagsByIssue.get(row.id) ?? []).map((t) => t.tag));
      const attachments = coerceAttachments(
        (attsByIssue.get(row.id) ?? []).map((a) => ({
          id: a.attachment_id,
          name: a.name,
          mimeType: a.mime_type,
          sizeBytes: a.size_bytes,
          addedAt: a.added_at,
        })),
      );
      const statusHistory: StatusEvent[] = (historyByIssue.get(row.id) ?? []).map((h) => ({
        status: h.status as Status,
        at: h.at,
        by: (h.by === "agent" ? "agent" : "user") as "user" | "agent",
      }));
      const record: RecordEntry[] = (recordByIssue.get(row.id) ?? []).map((r) => ({
        at: r.at,
        author: (r.author === "agent" ? "agent" : "user") as "user" | "agent",
        ...(r.source !== null ? { source: r.source } : {}),
        text: r.text,
      }));
      const links = coerceLinks(
        (linksBySource.get(row.id) ?? []).map((l) => ({ targetId: l.target_id, kind: l.kind })),
        row.id,
      );
      const commits = coerceCommits(
        (commitsByIssue.get(row.id) ?? []).map((c) => ({ sha: c.sha, at: c.at })),
      );

      return {
        id: row.id,
        number: row.number,
        title: row.title,
        type: row.type as IssueType,
        priority: row.priority as Priority,
        status: row.status as Status,
        description: row.description,
        verifyCriteria: row.verify_criteria,
        createdAt: row.created_at,
        resolvedAt: row.resolved_at,
        tasks,
        tags,
        attachments,
        statusHistory,
        record,
        links,
        commits,
        pendingClose: pendingCloseByIssue.get(row.id) ?? null,
        // NULLed by any older build's INSERT (its column list omits them) —
        // re-derive/fall back exactly like normalize() does for objects.
        guid: row.guid ?? deriveGuid(row.id, row.created_at),
        updatedAt: row.updated_at ?? row.created_at,
      };
    });
  }

  /**
   * Write one issue's eight-table fan-out. Caller is responsible for wrapping
   * in BEGIN/COMMIT (so multi-issue calls like replaceAll / mergeAll can run
   * as one transaction).
   */
  private writeIssueRows(db: Database, issue: Issue): void {
    db.run(
      `INSERT OR REPLACE INTO issues
         (id, number, title, description, verify_criteria, type, priority, status, created_at, resolved_at, guid, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        issue.id,
        issue.number,
        issue.title,
        issue.description ?? "",
        issue.verifyCriteria ?? "",
        issue.type,
        issue.priority,
        issue.status,
        issue.createdAt,
        issue.resolvedAt ?? null,
        issue.guid ?? null,
        issue.updatedAt ?? null,
      ],
    );

    // Delete-then-insert each child table: the webview ships full arrays on
    // every update, so partial-update semantics don't exist anywhere upstream.
    db.run("DELETE FROM issue_tasks WHERE issue_id = ?", [issue.id]);
    issue.tasks.forEach((t, i) => {
      db.run(
        "INSERT INTO issue_tasks (issue_id, task_id, position, text, done, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
        [issue.id, t.id, i, t.text, t.done ? 1 : 0, t.updatedAt ?? null],
      );
    });

    db.run("DELETE FROM issue_tags WHERE issue_id = ?", [issue.id]);
    issue.tags.forEach((tag, i) => {
      db.run(
        "INSERT OR IGNORE INTO issue_tags (issue_id, tag, position) VALUES (?, ?, ?)",
        [issue.id, tag, i],
      );
    });

    db.run("DELETE FROM issue_attachments WHERE issue_id = ?", [issue.id]);
    issue.attachments.forEach((a, i) => {
      db.run(
        `INSERT INTO issue_attachments
           (issue_id, attachment_id, position, name, mime_type, size_bytes, added_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [issue.id, a.id, i, a.name, a.mimeType, a.sizeBytes, a.addedAt],
      );
    });

    db.run("DELETE FROM issue_status_history WHERE issue_id = ?", [issue.id]);
    issue.statusHistory.forEach((h, i) => {
      db.run(
        "INSERT INTO issue_status_history (issue_id, position, status, at, by) VALUES (?, ?, ?, ?, ?)",
        [issue.id, i, h.status, h.at, h.by ?? "user"],
      );
    });

    db.run("DELETE FROM issue_record WHERE issue_id = ?", [issue.id]);
    issue.record.forEach((r, i) => {
      db.run(
        "INSERT INTO issue_record (issue_id, position, at, author, source, text) VALUES (?, ?, ?, ?, ?, ?)",
        [issue.id, i, r.at, r.author, r.source ?? null, r.text],
      );
    });

    db.run("DELETE FROM issue_links WHERE source_id = ?", [issue.id]);
    (issue.links ?? []).forEach((l, i) => {
      // Foreign-key constraints on target_id will reject unknown targets at
      // INSERT time. We expect callers to have already filtered via
      // validateLinks; INSERT OR IGNORE keeps a stray bad entry from rolling
      // back the entire transaction.
      db.run(
        "INSERT OR IGNORE INTO issue_links (source_id, target_id, kind, position) VALUES (?, ?, ?, ?)",
        [issue.id, l.targetId, l.kind, i],
      );
    });

    db.run("DELETE FROM issue_commits WHERE issue_id = ?", [issue.id]);
    (issue.commits ?? []).forEach((c, i) => {
      // PK (issue_id, sha): OR IGNORE keeps a stray duplicate sha from rolling
      // back the transaction (coercers upstream already dedupe).
      db.run(
        "INSERT OR IGNORE INTO issue_commits (issue_id, sha, at, position) VALUES (?, ?, ?, ?)",
        [issue.id, c.sha, c.at, i],
      );
    });

    db.run("DELETE FROM issue_pending_close WHERE issue_id = ?", [issue.id]);
    if (issue.pendingClose) {
      db.run(
        "INSERT INTO issue_pending_close (issue_id, by, note, at, target) VALUES (?, ?, ?, ?, ?)",
        [
          issue.id,
          issue.pendingClose.by,
          issue.pendingClose.note ?? null,
          issue.pendingClose.at,
          issue.pendingClose.target ?? null,
        ],
      );
    }
  }

  private runInTransaction(fn: () => void): void {
    if (!this.db) throw new Error("DB not initialised");
    this.db.run("BEGIN");
    try {
      fn();
      this.db.run("COMMIT");
    } catch (e) {
      try { this.db.run("ROLLBACK"); } catch {}
      throw e;
    }
  }

  private getSchemaMeta(db: Database, key: string): string | null {
    const rows = selectAll<{ value: string }>(
      db,
      "SELECT value FROM schema_meta WHERE key = ?",
      [key],
    );
    return rows.length > 0 ? rows[0]!.value : null;
  }

  private setSchemaMeta(db: Database, key: string, value: string): void {
    db.run("INSERT OR REPLACE INTO schema_meta (key, value) VALUES (?, ?)", [key, value]);
  }

  /**
   * Persist the in-memory DB to `<storageDir>/dostuff.db` via tmp-file +
   * rename (atomic on POSIX; survives a crash mid-write).
   *
   * Serialized + coalescing (concurrency L1): at most one write is in flight;
   * a call arriving mid-write queues exactly one follow-up export that
   * snapshots the DB *after* the current write finishes — so it includes the
   * caller's mutation, and N concurrent callers coalesce into that single
   * follow-up. Latest-state-wins, like the sync debounce. Without this, two
   * overlapping exports could rename in the wrong order and persist stale
   * bytes until the next write.
   */
  /**
   * Write-behind chokepoint for every mutator. With a delay, marks the store
   * dirty and (re)arms one trailing timer; with `persistDelayMs: 0` it awaits
   * the write like the pre-2.1 code did.
   */
  private schedulePersist(): Promise<void> {
    this.dirty = true;
    if (this.persistDelayMs <= 0) return this.persistNow();
    if (!this.persistTimer) {
      this.persistTimer = setTimeout(() => {
        this.persistTimer = null;
        void this.persistNow().catch((e) => {
          this.appendLog(`Persist failed: ${e instanceof Error ? e.message : String(e)}`);
        });
      }, this.persistDelayMs);
    }
    return Promise.resolve();
  }

  private persistNow(): Promise<void> {
    this.dirty = false;
    return this.db ? this.exportDb() : this.persistKv();
  }

  /** Persist any pending mutation now and wait for in-flight writes to land. */
  async flush(): Promise<void> {
    if (this.persistTimer) {
      clearTimeout(this.persistTimer);
      this.persistTimer = null;
    }
    if (this.dirty) await this.persistNow();
    // Whatever was already running (or queued behind it) must finish too.
    while (this.exportRunning || this.exportQueued) {
      await (this.exportQueued ?? this.exportRunning);
    }
  }

  /** `flush()` then `dispose()` — the shutdown path for hosts that can await. */
  async close(): Promise<void> {
    await this.flush();
    this.dispose();
  }

  private exportDb(): Promise<void> {
    if (!this.db) return Promise.resolve();
    if (this.exportRunning) {
      if (!this.exportQueued) {
        this.exportQueued = this.exportRunning.then(() => {
          this.exportQueued = null;
          return this.exportDb();
        });
      }
      return this.exportQueued;
    }
    const run = this.doExportDb();
    // Track completion without propagating the error twice — the caller gets
    // the rejection from `run`; the tracking promise must never be unhandled.
    this.exportRunning = run.then(
      () => {
        this.exportRunning = null;
      },
      () => {
        this.exportRunning = null;
      },
    );
    return run;
  }

  private async doExportDb(): Promise<void> {
    if (!this.db) return;
    const folder = this.host.storageDir();
    if (!folder) return;
    const bytes = this.db.export();
    const tmpPath = nodePath.join(folder, DB_TMP_FILENAME);
    const dbPath = nodePath.join(folder, DB_FILENAME);
    await this.fs.writeFile(tmpPath, bytes);
    try {
      await this.fs.rename(tmpPath, dbPath);
    } catch {
      // Fallback for FS providers that don't implement rename (defensive — the
      // built-in fs provider does). The non-atomic path still ends up correct.
      await this.fs.writeFile(dbPath, bytes);
      try { await this.fs.delete(tmpPath); } catch {}
    }
  }

  private closeDb(): void {
    if (this.db) {
      try { this.db.close(); } catch {}
      this.db = null;
    }
  }

  // ─── KV fallback ────────────────────────────────────────────────────────

  private loadFromKv(): Issue[] {
    const raw = this.host.kv?.get() ?? [];
    if (!Array.isArray(raw)) return [];
    return raw.map((entry) => {
      const { issue, coerced } = normalize(entry as Issue);
      if (coerced.length) {
        this.appendLog(`Coerced fields on ${issue.id} (globalState): ${coerced.join(", ")}`);
      }
      return issue;
    });
  }

  private async persistKv(): Promise<void> {
    await this.host.kv?.update(this.cache);
  }

  /**
   * Synchronous (VSCode's `Disposable` contract). A pending write-behind is
   * snapshotted and its file write started, but cannot be awaited here —
   * hosts that can wait use `close()` (headless) or `flush()` from
   * `deactivate()` (extension).
   */
  dispose() {
    if (this.persistTimer) {
      clearTimeout(this.persistTimer);
      this.persistTimer = null;
    }
    if (this.dirty) void this.persistNow().catch(() => {});
    this.closeDb();
    this.emitter.dispose();
    this.logger.dispose?.();
  }
}

// ─── helpers ────────────────────────────────────────────────────────────

/**
 * Per-task diff-stamping (docs/plans/ticket-sync/01 §5): a task id absent from
 * `prior` is new (→ `now`); present with identical text+done carries the
 * *prior* stamp forward (the webview strips the field, so reconciliation must
 * happen here — and any smuggled incoming stamp is discarded); changed → `now`.
 */
function stampTasks(next: Task[], prior: Task[] | undefined, now: string): Task[] {
  const priorById = new Map((prior ?? []).map((t) => [t.id, t]));
  return next.map((t) => {
    const p = priorById.get(t.id);
    if (!p) return { ...t, updatedAt: now };
    if (p.text === t.text && p.done === t.done) {
      const { updatedAt: _incoming, ...rest } = t;
      return p.updatedAt ? { ...rest, updatedAt: p.updatedAt } : rest;
    }
    return { ...t, updatedAt: now };
  });
}

/**
 * Import-path stamping (replaceAll / mergeAll): only-if-missing, so an
 * export→import round trip preserves exported guids and timestamps.
 */
function ensureSyncFields(issue: Issue): Issue {
  const { guid, updatedAt } = backfillSyncFields(issue.id, issue.createdAt, issue.guid, issue.updatedAt);
  if (guid === issue.guid && updatedAt === issue.updatedAt) return issue;
  return { ...issue, guid, updatedAt };
}

function selectAll<T extends Record<string, unknown>>(
  db: Database,
  sql: string,
  params: (string | number | null)[] = [],
): T[] {
  const stmt = db.prepare(sql);
  try {
    stmt.bind(params);
    const out: T[] = [];
    while (stmt.step()) {
      out.push(stmt.getAsObject() as unknown as T);
    }
    return out;
  } finally {
    stmt.free();
  }
}

function groupBy<T, K>(rows: T[], key: (r: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const r of rows) {
    const k = key(r);
    const arr = m.get(k);
    if (arr) arr.push(r);
    else m.set(k, [r]);
  }
  return m;
}
